### ISSUE TITLE
如何设置 Pod 里的 imagePullPolicy

### ISSUE THREAD

**Issue by wenbinye** [TarsCloud/K8SFramework#1]
现在默认的 imagePullPolicy 是 Always，有没有办法定制这个值？

**Comment by zhixiongdu027** [comment]
在当前的 APIVersion 中, 确实 无法通过 TServe 修改 imagePullPolicy,
但你可以找到对应的 Statefulet 资源， 然后手动修改 imagePullPolicy 字段.

正在计划中的下一个 APIVersion 的首要目标是支持更多的定制化属性, 可能会支持你的用法.

**Comment by ruanshudong** [comment]
新版已经支持了, tserver增加了这个配置
