### ISSUE TITLE
为什么要限制同一个 Server 中不同 Servant 监听端口号不允许重复

### ISSUE THREAD

**Issue by wenbinye** [TarsCloud/K8SFramework#5]
在 tarscontroller 中会检查 servant 端口号必须不同，这是出于什么考虑？
同一个应用服务，可能会提供不同服务接口，使用不同的 servant 名字，但是可以在同一个监听端口中处理的。现在强制端口号不同，服务端需要启动多个监听端口，客户端也不能重用连接。想了解一下有什么必要需要做这个验证？

**Comment by ruanshudong** [comment]
一个服务, servant名字和端口号是一对一的, 目前这是技术框架决定了, 最早就是这样设计的, 考虑历史兼容性, 这个一直延续下来, 以后估计也应该不会改变了.
