### ISSUE TITLE
TServer reconcile 频繁发生错误

### ISSUE THREAD

**Issue by wenbinye** [TarsCloud/K8SFramework#6]
在 tarscontoller 日志中出现很多这样的错误：
```
E1217 12:36:04.627593       1 tserver.go:160] patch tserver tars-test/chain-marketing error: Operation cannot be fulfilled on tservers.k8s.tars.io "chain-marketing": the object has been modified; please apply your changes to the latest version and try again
E1217 12:36:16.271580       1 tendpoint.go:292] update tendpoint tars-dev/chain-marketing error: Operation cannot be fulfilled on tendpoints.k8s.tars.io "chain-marketing": the object has been modified; please apply your changes to the latest version and try again
```
出现这种错误后就会出现 Pod 重新创建：
![截屏2021-12-18 上午9 56 53](https://user-images.githubusercontent.com/1221975/146625295-8e16d8ae-73cd-468b-b260-64fb4a68d424.png)

请问出现这种错误的原因是什么？可以避免吗？

**Comment by zhixiongdu027** [comment]
> 在 tarscontoller 日志中出现很多这样的错误：
> 
> ```
> E1217 12:36:04.627593       1 tserver.go:160] patch tserver tars-test/chain-marketing error: Operation cannot be fulfilled on tservers.k8s.tars.io "chain-marketing": the object has been modified; please apply your changes to the latest version and try again
> E1217 12:36:16.271580       1 tendpoint.go:292] update tendpoint tars-dev/chain-marketing error: Operation cannot be fulfilled on tendpoints.k8s.tars.io "chain-marketing": the object has been modified; please apply your changes to the latest version and try again
> ```
> 请问出现这种错误的原因是什么？可以避免吗？

你好，这种错误是 tarcontroller 在调谐 tserver ,tendpoint 资源时, 因为 缓存资源版本(k8s api 的 cache.informers 机制 )与 etcd中存储的资源版本不一致而导致的, 这种错误本身就是控制器模式的工作机制，无法也无需避免.
       
       

>  出现这种错误后就会出现 Pod 重新创建

tarscontroller 不会主动删除 Pod, 重新创建可能因为 Pod内的前台进程(tafnode) 执行失败导致 Pod退出，然后由 K8S 建立新的Pod .

**Comment by zhixiongdu027** [comment]
@wenbinye
Hello, I have already sent you a gmail, please check
Maybe we can help you with debugging.
