### ISSUE TITLE
Ingress 使用的api resource版本已弃用

### ISSUE THREAD

**Issue by CCNUwfh** [TarsCloud/K8SFramework#7]
install/tarsframework/templates/tars-tarsweb.yaml line:139 
ingress安装使用的api resource networking.k8s.io/v1beta1 在k8s v1.22 中已经弃用，使用helm进行快速安装时报错。

**Comment by ruanshudong** [comment]
已知问题, 下一个版本适配, 或者你根据1.2以上的版本适配改一下, 提交一个pr, 要不手头上还没有k8s这个版本, 还得升级, 比较麻烦

**Comment by lbbniu** [comment]
https://github.com/TarsCloud/K8SFramework/pull/8 适配所有已知版本 ingress
